name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Mink:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ddev/github-action-setup-ddev@v1

      - name: Install dependencies
        run: ddev composer install

      - name: Run tests
        run: ddev exec phpunit test/Test/WebDriver/SeleniumWebDriverTest.php
