name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true



jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: ddev/github-action-setup-ddev@v1

      - name: Setup PHP Version
        run: ddev config --php-version ${{ matrix.php }}

      - name: Install dependencies
        run: ddev composer install

      - name: Run tests
        run: |
          ddev exec phpunit test/Test/WebDriver/SeleniumWebDriverTest.php --fail-on-skipped
          ddev exec phpunit test/Test/WebDriver/ChromeDriverTest.php --fail-on-skipped
